version: 2.1

orbs:
  docker: circleci/docker@2.4.0

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          context: [docker-hub-creds]
          name: "Publish 'latest', currently 8.2"
          path: ./php8.2
          image: thebiggive/php
          tag: 'latest'
      - docker/publish:
          context: [docker-hub-creds]
          name: "Publish '8.1'"
          path: ./php8.1
          image: thebiggive/php
          tag: '8.1'
      - docker/publish:
          context: [docker-hub-creds]
          name: "Publish '8.2'"
          path: ./php8.2
          image: thebiggive/php
          tag: '8.2'
      - docker/publish:
          context: [docker-hub-creds]
          name: "Publish '8.3'"
          path: ./php8.3
          image: thebiggive/php
          tag: '8.3'
#      - docker/publish:
#          context: [docker-hub-creds]
#          name: "Publish 'dev-8.2'"
#          path: ./php8.2/dev
#          image: thebiggive/php
#          tag: 'dev-8.2'
#      - docker/publish:
#          context: [docker-hub-creds]
#          name: "Publish 'dev-8.3'"
#          path: ./php8.3/dev
#          image: thebiggive/php
#          tag: 'dev-8.3'
    triggers:
      - schedule:
          cron: "5 5 * * *"
          filters:
            branches:
              only:
                - main
