version: 2.1

orbs:
  docker: circleci/docker@2.7.2

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          context: [docker-hub-creds]
          docker-password: DOCKER_HUB_ACCESS_TOKEN
          docker-username: DOCKER_HUB_USERNAME
          name: "Publish 'latest', currently 8.3"
          path: ./php8.3
          image: thebiggive/php
          tag: 'latest'
      - docker/publish:
          context: [docker-hub-creds]
          docker-password: DOCKER_HUB_ACCESS_TOKEN
          docker-username: DOCKER_HUB_USERNAME
          name: "Publish '8.3'"
          path: ./php8.3
          image: thebiggive/php
          tag: '8.3'
      - docker/publish:
          context: [docker-hub-creds]
          docker-password: DOCKER_HUB_ACCESS_TOKEN
          docker-username: DOCKER_HUB_USERNAME
          name: "Publish 'dev-8.3'"
          path: ./php8.3/dev
          image: thebiggive/php
          tag: 'dev-8.3'
    triggers:
      - schedule:
          cron: "5 5 * * *"
          filters:
            branches:
              only:
                - main
