version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          context:
            - docker-hub-creds
          docker-password: DOCKER_HUB_ACCESS_TOKEN
          docker-username: DOCKER_HUB_USERNAME
          image: thebiggive/php
          tag: '8.1'
    triggers:
      - schedule:
          cron: "5 5 * * *"
          filters:
            branches:
              only:
                - main
